services:
  dbpsql:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGUSER=postgres
      - PGPASSWORD=root
    volumes:
      - ./pg-data:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  db-init:
    image: postgres:16
    command: pg_restore -d udb -U postgres -h dbpsql /tmp/dvdrental.tar
    volumes:
      - ./dvdrental.tar:/tmp/dvdrental.tar
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGPASSWORD=root
      - PGUSER=postgres
    depends_on:
      dbpsql:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin:rw
    depends_on:
      - dbpsql
